# =======================================
#   Auction System - Configuration
# =======================================
#   Dat file nay cung thu muc voi .jar
#   de chinh sua ma khong can rebuild
# =======================================

# --- Database MySQL ---
# Neu client va server cung 1 may: db.host=localhost
# Neu khac may: db.host=192.168.x.x (IP may cai MySQL)
db.host=localhost
db.port=3306
db.name=auction_system.db
db.user=root
db.pass=root
server.port=8080
stripe.secret.key=sk_test_51TbxFTFhOWjxP01qLb5ZPyqY8MvuPO8A6of9KdHrsDt40xBJ5bezOLFPPEHpaUnHS8BFKCTL6TFPKEvomh7PSqM0004xEma4x5